name: Add Submodule and Request Access

on:
  push:
    branches:
      - main

jobs:
  update_submodules:
    runs-on: ubuntu-latest

    steps:

      
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Git Submodules
      run: git submodule update --remote

  process_config:
    needs: update_submodules
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      # Limit: Important for next steps executions
      with: 
        fetch-depth: 0

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"      

    - name: Check for Changes in Config File
      id: ckeck_config
      run: |
        # Get the list of files changed in the current commit
        CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
    
        # Check if "projects.list" is in the list of changed files
        if echo "$CHANGED_FILES" | grep -q "projects.list"; then
          echo "::set-output name=config_changes::true"
        fi

    - name: Execute External Script
      #if: steps.ckeck_config.outputs.config_changes != ''
      run: |
        echo "projects.list has been changed."
        echo $SHELL
        echo $(pwd)
        ls
        # chmod +x submodule.sh
        action_sh="project.sh"
        git update-index --chmod=+x project.sh
        ./project.sh ${{ secrets.GITHUB_TOKEN }}
      working-directory: ${{ github.workspace }}/.github/workflows/project/
