name: Add Submodule and Request Access

on:
  push:
    paths: 
      - '.github/workflows/project/**'

jobs:
  update_submodules:
    runs-on: ubuntu-latest

    steps:      
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Git Submodules
      run: git submodule update --remote --init

  process_config:
    needs: update_submodules
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      # Limit: Important for next steps executions
      with: 
        fetch-depth: 0

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"      

    - name: Check for Changes in Config File
      id: ckeck_config
      run: |
        # Get the list of files changed in the current commit
        CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
    
        # Check if "projects.list" is in the list of changed files
        if echo "$CHANGED_FILES" | grep -q "projects.list"; then
          echo "::set-output name=config_changes::true"
        fi

    - name: Add project submodule
      if: steps.ckeck_config.outputs.config_changes != ''
      env:
        ORG_TOKEN: ${{ secrets.ORG4G_SECRET }}
      run: |
        echo "projects.list has been changed."
        # git update-index --chmod=+x ./project/project.sh
        chmod +x ./project/project.sh
        ./project/project.sh $ORG_TOKEN

    - name: Commit Changes
      if: steps.ckeck_config.outputs.config_changes != ''
      run: |
        git config user.name "${{ github.repository_owner }}"       
        git add .
        git commit -m "Action: Submodules management"
      working-directory: ${{ github.workspace }}

    - name: Push Changes
      if: steps.ckeck_config.outputs.config_changes != ''  
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ORG4G_SECRET }}
