name: Add Submodule and Request Access

on:
  push:
    branches:
      - main

jobs:
  update_submodules:
    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git Submodules
      run: git submodule update --remote

  process_config:
    needs: update_submodules
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check for Changes in Config File
      id: config_changes
      run: |
        CHANGES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "projects.list")
        echo "::set-output name=config_changes::${CHANGES}"
      working-directory: ${{ github.workspace }}

    - name: Execute External Script
      if: steps.config_changes.outputs.config_changes != ''
      run: |
        chmod +x submodule.sh
        ./submodule.sh ${{ secrets.GITHUB_TOKEN }}
      working-directory: ${{ github.workspace }}
